### ISSUE TITLE
Unable to Build mm-hammer on ARM64 Due to Missing `hhutils` Binaries

### ISSUE THREAD

**Issue by volisoft** [digama0/mm-hammer#2]
I'm attempting to build `mm-hammer` on an ARM64 platform (Linux 6.11.0 aarch64 GNU/Linux), but I'm encountering **exec format errors** with `hhutils` and `vampire`. 

- I managed to compile `vampire` from its source code, as it's available. 
- However, I've been unable to locate an ARM version of `hhutils`, which appears to be built only for x64 architecture.

Could you provide:
1. Sources for `hhutils`, or 
2. ARM64 compatible binaries for `hhutils`?

Thank you for your assistance.

**Comment by digama0** [comment]
@JUrban I also want to know the answer to this question.

**Comment by JUrban** [comment]
Cezary Kaliszyk (the author of the C++ version of the ML utilities
originally used for Holyhammer and MizAR) tells me that the C++ source code
is publicly available as a part of CoqHammer:
https://github.com/lukaszcz/coqhammer/tree/coq8.20/src/predict .
